
USE [DWOS]
GO

-- Update Database Version
DECLARE @currentVersion nvarchar(50) = '13.2.0'


IF NOT EXISTS (SELECT * FROM [ApplicationSettings] WHERE [SettingName] = 'DatabaseVersion')
	INSERT INTO [dbo].[ApplicationSettings] ([SettingName],[Value]) VALUES ('DatabaseVersion',@currentVersion)
ELSE
	UPDATE [dbo].[ApplicationSettings] SET [Value] = @currentVersion WHERE  [SettingName] = 'DatabaseVersion'
GO




-- Update Order Status to include Part Quantity

/****** Object:  StoredProcedure [dbo].[Get_OrderStatus]    Script Date: 4/16/2013 10:43:49 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[Get_OrderStatus] 
AS
BEGIN
	SET NOCOUNT ON;

SELECT        [Order].OrderID AS WO, [Order].PurchaseOrder AS PO, Customer.Name AS Customer, Part.Name AS Part, [Order].EstShipDate, [Order].Priority, [Order].WorkStatus, 
                         [Order].CurrentLocation, dbo.fnGetNextDept([Order].OrderID) AS NextDept, dbo.fnGetCurrentProcess([Order].OrderID) AS CurrentProcess, [Order].IsRework, 
                         [Order].PartQuantity
FROM            [Order] LEFT OUTER JOIN
                         Customer ON [Order].CustomerID = Customer.CustomerID LEFT OUTER JOIN
                         Part ON [Order].PartID = Part.PartID
WHERE        ([Order].Status = N'Open')
					 
END



-- Update new report notification template

INSERT INTO [dbo].[Templates]
           ([TemplateID]
           ,[Template]
           ,[Description]
           ,[Tokens])
     VALUES
           ('ReportNotification'
           ,'<html>
<head>
    <title>Dynamic Paint Solutions - Report Notification</title>
</head>
<body>
    <table style="width: 800px">
        <tr style="font-family: Arial; color: maroon; font-size: 22px; font-weight: bold;">
            <td style="text-align: center">
                <img src="%LOGO%">
            </td>
        </tr>
        <tr>
            <td style="font-family: Verdana; font-size: 12px; font-weight: normal; padding: 3px; margin: auto;">
               Attached is the ‘%REPORTNAME%’ Report that you requested to be emailed to you. If you have any questions, then please contact your <a href="mailto:sales@dynamicpaintsolutions.com">DPS sales representative</a>.<br/><br/>
               Thank You,<br><br>
            </td>
        </tr>
        <tr style="font-family: Arial; font-size: 16px; font-weight: bold;">
            <td>
                <a href="http://www.dynamicpaintsolutions.com" style="color: blue">Dynamic Paint Solutions</a>
            </td>
        </tr>
        <tr>
            <td style="font-family: Verdana; font-size: 12px; font-weight: normal; padding: 3px; margin: auto;">
                415 Airport Road<br>
                Eastman, GA 31023<br>
                478.374.5402 Phone<br>
                478.374.5424 Fax</td>
        </tr>
    </table>
    <br>
    <div style="font-family: Verdana; font-size: 12px; font-weight: normal; padding: 3px; margin: 3px; display: inline-block; width: 800px; background-position: center center; background-repeat: no-repeat;">
        <p style="text-align: justify">Do not reply to this email address. This is an automated notification generated by Dynamic Paint Solutions. Please direct all communications to your <a href="mailto:sales@dynamicpaintsolutions.com">DPS sales representative</a>. ITAR/EAR technical data is restricted by the Arms Export Control Act (Title 22, U.S.C., Sec 2751) or the Export Administration Act (Title 50, U.S.C., App. 2401), as amended. Violations of these export laws are subject to severe      criminal penalties. The preceding information may be confidential or privileged. It only should be used or disseminated for the purpose of conducting business with Dynamic Paint Solutions. If you are not an intended recipient, please delete the information from your system. Thank you for your cooperation. Delivery truck deliveries will be delivered on your next scheduled delivery date.</p>
        <p>Please visit the <a href="https://dwos.dynamicpaintsolutions.com">Dynamic Paint Solutions Customer Portal</a> to view order status, print COC, and run reports. If you have not registered for the portal, then please contact your <a href="mailto:sales@dynamicpaintsolutions.com">DPS sales representative</a>.</p>
    </div>

</body>
</html>'
           ,'Email template to send customers automated reports.'
           ,'%REPORTNAME%,  %LOGO%')
GO


-- Add ReportType Table 

/****** Object:  Table [dbo].[ReportType]    Script Date: 4/23/2013 2:50:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ReportType](
	[ReportTypeID] [int] IDENTITY(1,1) NOT NULL,
	[DisplayName] [nvarchar](50) NOT NULL,
	[AssemblyName] [nvarchar](50) NOT NULL,
	[TypeName] [nvarchar](50) NOT NULL,
	[DefaultSchedule] [nvarchar](50) NULL,
 CONSTRAINT [PK_ReportType] PRIMARY KEY CLUSTERED 
(
	[ReportTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

-- Add ReportTask Table

/****** Object:  Table [dbo].[ReportTask]    Script Date: 4/23/2013 2:50:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ReportTask](
	[ReportTaskID] [int] IDENTITY(1,1) NOT NULL,
	[ContactID] [int] NOT NULL,
	[ReportTypeID] [int] NOT NULL,
	[Schedule] [nvarchar](50) NOT NULL,
	[LastRun] [datetime] NOT NULL,
 CONSTRAINT [PK_ReportTask] PRIMARY KEY CLUSTERED 
(
	[ReportTaskID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ReportTask] ADD  CONSTRAINT [DF_ReportTask_LastRun]  DEFAULT ('1/1/2000') FOR [LastRun]
GO

ALTER TABLE [dbo].[ReportTask]  WITH CHECK ADD  CONSTRAINT [FK_ReportTask_d_Contact] FOREIGN KEY([ContactID])
REFERENCES [dbo].[d_Contact] ([ContactID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ReportTask] CHECK CONSTRAINT [FK_ReportTask_d_Contact]
GO

ALTER TABLE [dbo].[ReportTask]  WITH CHECK ADD  CONSTRAINT [FK_ReportTask_ReportType] FOREIGN KEY([ReportTypeID])
REFERENCES [dbo].[ReportType] ([ReportTypeID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ReportTask] CHECK CONSTRAINT [FK_ReportTask_ReportType]
GO


-- Add default report types

INSERT INTO [dbo].[ReportType]
           ([DisplayName],[AssemblyName],[TypeName],[DefaultSchedule])
     VALUES
           ('Orde Status', 'DWOS.Reports',	'CurrentOrderStatusReport',	'0 20 1 ? * MON-FRI')



-- Add Report Security Group


INSERT INTO [dbo].[SecurityRole]
           ([SecurityRoleID]
           ,[Description]
           ,[SecurityRoleCategoryID])
     VALUES
           ('OrderStatusByCustomer', 'Ability to run Order Status By Customer Report.',	'Reports')
GO

INSERT INTO [dbo].[SecurityGroup_Role]
           ([SecurtyGroupID]
           ,[SecurityRoleID])
     VALUES
           (1,'OrderStatusByCustomer')
GO



INSERT INTO [dbo].[SecurityRole]
           ([SecurityRoleID]
           ,[Description]
           ,[SecurityRoleCategoryID])
     VALUES
           ('InspectionReport', 'Ability to run the Inspection Report.',	'Reports')
GO

INSERT INTO [dbo].[SecurityGroup_Role]
           ([SecurtyGroupID]
           ,[SecurityRoleID])
     VALUES
           (1,'InspectionReport')
GO

-- Add Order Delete Security Group


INSERT INTO [dbo].[SecurityRole]
           ([SecurityRoleID]
           ,[Description]
           ,[SecurityRoleCategoryID])
     VALUES
           ('OrderEntry.OrderDelete', 'Ability to delete orders in order entry.',	'Sales')
GO

INSERT INTO [dbo].[SecurityGroup_Role]
           ([SecurtyGroupID]
           ,[SecurityRoleID])
     VALUES
           (1,'OrderEntry.OrderDelete')
GO


