-- Update Database Version
DECLARE @currentVersion nvarchar(50) = '17.2.1'

IF NOT EXISTS (SELECT * FROM [ApplicationSettings] WHERE [SettingName] = 'DatabaseVersion')
    INSERT INTO [dbo].[ApplicationSettings] ([SettingName],[Value]) VALUES ('DatabaseVersion',@currentVersion)
ELSE
    UPDATE [dbo].[ApplicationSettings] SET [Value] = @currentVersion WHERE  [SettingName] = 'DatabaseVersion'
GO

--
-- IsVisible column for Custom Field - show/hide throughout DWOS
--
ALTER TABLE dbo.CustomField ADD
    IsVisible bit NOT NULL CONSTRAINT DF_CustomField_IsVisible DEFAULT 1
GO

--
-- Shipment package types
--

CREATE TABLE dbo.ShipmentPackageType
    (
    ShipmentPackageTypeID int NOT NULL IDENTITY (1, 1),
    Name nvarchar(10) NOT NULL
    )  ON [PRIMARY]
GO

ALTER TABLE dbo.ShipmentPackageType ADD CONSTRAINT
    PK_ShipmentPackageType PRIMARY KEY CLUSTERED 
    (
    ShipmentPackageTypeID
    ) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.ShipmentPackageType ADD CONSTRAINT
    AK_ShipmentPackageType UNIQUE NONCLUSTERED 
    (
    Name
    ) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

-- Default package type - 
SET IDENTITY_INSERT ShipmentPackageType ON

INSERT INTO ShipmentPackageType (
    ShipmentPackageTypeID,
    Name
    )
VALUES (
    1,
    'Box'
    );

SET IDENTITY_INSERT ShipmentPackageType OFF

GO

ALTER TABLE dbo.ShipmentPackage ADD
    ShipmentPackageTypeID int NOT NULL CONSTRAINT DF_ShipmentPackage_ShipmentPackageTypeID DEFAULT 1
GO
ALTER TABLE dbo.ShipmentPackage ADD CONSTRAINT
    FK_ShipmentPackage_ShipmentPackageType FOREIGN KEY
    (
    ShipmentPackageTypeID
    ) REFERENCES dbo.ShipmentPackageType
    (
    ShipmentPackageTypeID
    ) ON UPDATE  CASCADE 
     ON DELETE  NO ACTION 

GO

-- Permission for editing shipment package types
INSERT INTO [dbo].[SecurityRole]([SecurityRoleID], [Description], [SecurityRoleCategoryID])
    VALUES ('ShipmentContainerTypeManager', 'Ability to edit shipment container types.', 'Managers')
GO

-- 'Show on documents' option for rework reasons
ALTER TABLE dbo.d_ReworkReason ADD
    ShowOnDocuments bit NOT NULL CONSTRAINT DF_d_ReworkReason_ShowOnDocuments DEFAULT 0
GO

--
-- Certificate notifications
--

-- Contact option
ALTER TABLE dbo.d_Contact ADD
    COCNotification bit NOT NULL CONSTRAINT DF_d_Contact_COCNotification DEFAULT 0
GO

-- Notification template
INSERT INTO [dbo].[Templates] (
    [TemplateID],
    [Template],
    [Description],
    [Tokens]
    )
VALUES (
    'CertificateNotification',
    '<html>
<head>
    <title>%COMPANY% - Certificate Notification - %ORDERTYPE% %ORDER%</title>
</head>
<body>
    <table style="width: 800px">
        <tr style="font-family: Arial; color: maroon; font-size: 22px; font-weight: bold;">
            <td style="text-align: center">
                <img src="%LOGO%" style="width: 200px">
            </td>
        </tr>
        <tr>
            <td style="font-family: Verdana; font-size: 12px; font-weight: normal; padding: 3px; margin: auto;">Attached is the certificate for %ORDERTYPE% %ORDER%. If you have any questions, then please contact your <a href="mailto:%COMPANY_EMAIL%">%COMPANY% sales representative</a>.<br />
                <br />
                Thank You,<br>
                <br>
            </td>
        </tr>
        <tr style="font-family: Arial; font-size: 16px; font-weight: bold;">
            <td>
                <a href="%COMPANY_URL%" style="color: blue">%COMPANY%</a>
            </td>
        </tr>
        <tr>
            <td style="font-family: Verdana; font-size: 12px; font-weight: normal; padding: 3px; margin: auto;">
                %COMPANY_ADDRESS%<br>
                %COMPANY_CITY%, %COMPANY_STATE% %COMPANY_ZIP%<br>
                %COMPANY_PHONE% Phone<br>
                %COMPANY_FAX% Fax
            </td>
        </tr>
    </table>
    <br>
    <div style="font-family: Verdana; font-size: 12px; font-weight: normal; padding: 3px; margin: 3px; display: inline-block; width: 800px; background-position: center center; background-repeat: no-repeat;">
        <p style="text-align: justify">Do not reply to this email address. This is an automated notification generated by %COMPANY%. Please direct all communications to your <a href="mailto:%COMPANY_EMAIL%">%COMPANY% sales representative</a>. ITAR/EAR technical data is restricted by the Arms Export Control Act (Title 22, U.S.C., Sec 2751) or the Export Administration Act (Title 50, U.S.C., App. 2401), as amended. Violations of these export laws are subject to severe criminal penalties. The preceding information may be confidential or privileged. It only should be used or disseminated for the purpose of conducting business with %COMPANY%. If you are not an intended recipient, please delete the information from your system. Thank you for your cooperation. Delivery truck deliveries will be delivered on your next scheduled delivery date.</p>
        Please visit the <a href="%PORTAL_URL%">%COMPANY% Customer Portal</a> to view order status, print COC, and run reports. If you have not registered for the portal, then please contact your <a href="mailto:%COMPANY_EMAIL%">%COMPANY% sales representative</a>.
    </div>
</body>
</html>',
    'Email template to notify customer that a certificate has been made for an order.',
    '%ORDER%,%ORDERTYPE%,%LOGO%'
    );

GO

-- COC Notifications
CREATE TABLE dbo.COCNotification
    (
    COCNotificationID int NOT NULL IDENTITY (1, 1),
    COCID int NOT NULL,
    ContactID int NOT NULL,
    NotificationSent datetime2(7) NULL
    )  ON [PRIMARY]
GO
ALTER TABLE dbo.COCNotification ADD CONSTRAINT
    PK_COCNotification PRIMARY KEY CLUSTERED 
    (
    COCNotificationID
    ) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.COCNotification ADD CONSTRAINT
    FK_COCNotification_COC FOREIGN KEY
    (
    COCID
    ) REFERENCES dbo.COC
    (
    COCID
    ) ON UPDATE  CASCADE 
     ON DELETE  CASCADE 

GO
ALTER TABLE dbo.COCNotification ADD CONSTRAINT
    FK_COCNotification_d_Contact FOREIGN KEY
    (
    ContactID
    ) REFERENCES dbo.d_Contact
    (
    ContactID
    ) ON UPDATE  CASCADE 
     ON DELETE  CASCADE 

GO

-- Bulk Certificate Notifications
CREATE TABLE dbo.BulkCOCNotification
    (
    BulkCOCNotificationID int NOT NULL IDENTITY (1, 1),
    BulkCOCID int NOT NULL,
    ContactID int NOT NULL,
    NotificationSent datetime2(7) NULL
    )  ON [PRIMARY]
GO
ALTER TABLE dbo.BulkCOCNotification ADD CONSTRAINT
    PK_BulkCOCNotification PRIMARY KEY CLUSTERED 
    (
    BulkCOCNotificationID
    ) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.BulkCOCNotification ADD CONSTRAINT
    FK_BulkCOCNotification_BulkCOC FOREIGN KEY
    (
    BulkCOCID
    ) REFERENCES dbo.BulkCOC
    (
    BulkCOCID
    ) ON UPDATE  CASCADE
     ON DELETE  CASCADE

GO
ALTER TABLE dbo.BulkCOCNotification ADD CONSTRAINT
    FK_BulkCOCNotification_d_Contact FOREIGN KEY
    (
    ContactID
    ) REFERENCES dbo.d_Contact
    (
    ContactID
    ) ON UPDATE  CASCADE
     ON DELETE  CASCADE

GO
