//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWOS.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open")]
        public string OrderStatusOpen {
            get {
                return ((string)(this["OrderStatusOpen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string OrderPriorityDefault {
            get {
                return ((string)(this["OrderPriorityDefault"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paint")]
        public string CurrentDepartment {
            get {
                return ((string)(this["CurrentDepartment"]));
            }
            set {
                this["CurrentDepartment"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Closed")]
        public string OrderStatusClosed {
            get {
                return ((string)(this["OrderStatusClosed"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedCustomer {
            get {
                return ((string)(this["LastSelectedCustomer"]));
            }
            set {
                this["LastSelectedCustomer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedProcess {
            get {
                return ((string)(this["LastSelectedProcess"]));
            }
            set {
                this["LastSelectedProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedUser {
            get {
                return ((string)(this["LastSelectedUser"]));
            }
            set {
                this["LastSelectedUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedPart {
            get {
                return ((string)(this["LastSelectedPart"]));
            }
            set {
                this["LastSelectedPart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScannedPODirectory {
            get {
                return ((string)(this["ScannedPODirectory"]));
            }
            set {
                this["ScannedPODirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal MinimumOrderRushCharge {
            get {
                return ((decimal)(this["MinimumOrderRushCharge"]));
            }
            set {
                this["MinimumOrderRushCharge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PrintQuantity {
            get {
                return ((int)(this["PrintQuantity"]));
            }
            set {
                this["PrintQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int OrderMaxNumberofDays {
            get {
                return ((int)(this["OrderMaxNumberofDays"]));
            }
            set {
                this["OrderMaxNumberofDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PartManagerMediaDirectory {
            get {
                return ((string)(this["PartManagerMediaDirectory"]));
            }
            set {
                this["PartManagerMediaDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Expedite")]
        public string OrderPriorityExpedite {
            get {
                return ((string)(this["OrderPriorityExpedite"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08/10/2011 16:30:00")]
        public global::System.DateTime ShippingRolloverTime {
            get {
                return ((global::System.DateTime)(this["ShippingRolloverTime"]));
            }
            set {
                this["ShippingRolloverTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Late0Day {
            get {
                return ((global::System.Drawing.Color)(this["Late0Day"]));
            }
            set {
                this["Late0Day"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color Late1Day {
            get {
                return ((global::System.Drawing.Color)(this["Late1Day"]));
            }
            set {
                this["Late1Day"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color Late2Day {
            get {
                return ((global::System.Drawing.Color)(this["Late2Day"]));
            }
            set {
                this["Late2Day"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Late3Day {
            get {
                return ((global::System.Drawing.Color)(this["Late3Day"]));
            }
            set {
                this["Late3Day"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPS")]
        public string DefaultShippingCarrierID {
            get {
                return ((string)(this["DefaultShippingCarrierID"]));
            }
        }
        
        /// <summary>
        /// Hide buttons that are disabled that the user is not authorized to use.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Hide buttons that are disabled that the user is not authorized to use.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoHideDisabledButtons {
            get {
                return ((bool)(this["AutoHideDisabledButtons"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pin")]
        public global::DWOS.Data.LoginType UserLogInType {
            get {
                return ((global::DWOS.Data.LoginType)(this["UserLogInType"]));
            }
            set {
                this["UserLogInType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string PartMarkSelectedFont {
            get {
                return ((string)(this["PartMarkSelectedFont"]));
            }
            set {
                this["PartMarkSelectedFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MultiStroke1")]
        public string PartMarkSelectedStroke {
            get {
                return ((string)(this["PartMarkSelectedStroke"]));
            }
            set {
                this["PartMarkSelectedStroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVersionUpdateShown {
            get {
                return ((string)(this["LastVersionUpdateShown"]));
            }
            set {
                this["LastVersionUpdateShown"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QCguvMndJnRdD4QZTlXw")]
        public string UserVoiceAPIKey {
            get {
                return ((string)(this["UserVoiceAPIKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7aV8u2phiSuU5LKWWzk9FIMdrG9TRxzdmDJ0KrdlKA")]
        public string UserVoiceAPISecret {
            get {
                return ((string)(this["UserVoiceAPISecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dwos")]
        public string UserVoiceSubDomain {
            get {
                return ((string)(this["UserVoiceSubDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".lnk,.exe,.dll")]
        public string DocumentTypesToExclude {
            get {
                return ((string)(this["DocumentTypesToExclude"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TouchEnabled {
            get {
                return ((bool)(this["TouchEnabled"]));
            }
            set {
                this["TouchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintOrderProcessSheets {
            get {
                return ((bool)(this["PrintOrderProcessSheets"]));
            }
            set {
                this["PrintOrderProcessSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WIPAnimations {
            get {
                return ((bool)(this["WIPAnimations"]));
            }
            set {
                this["WIPAnimations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SummaryCountBy {
            get {
                return ((int)(this["SummaryCountBy"]));
            }
            set {
                this["SummaryCountBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SummaryLateBy {
            get {
                return ((int)(this["SummaryLateBy"]));
            }
            set {
                this["SummaryLateBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WIPHighlightLateFullRow {
            get {
                return ((bool)(this["WIPHighlightLateFullRow"]));
            }
            set {
                this["WIPHighlightLateFullRow"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("On Hold")]
        public string CustomerStatusOnHold {
            get {
                return ((string)(this["CustomerStatusOnHold"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedOrderReport {
            get {
                return ((string)(this["LastSelectedOrderReport"]));
            }
            set {
                this["LastSelectedOrderReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ReceivingPrintQuantity {
            get {
                return ((int)(this["ReceivingPrintQuantity"]));
            }
            set {
                this["ReceivingPrintQuantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FinalInspectionPrintLabel {
            get {
                return ((bool)(this["FinalInspectionPrintLabel"]));
            }
            set {
                this["FinalInspectionPrintLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int CurrentLine {
            get {
                return ((int)(this["CurrentLine"]));
            }
            set {
                this["CurrentLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PauseRefreshWithOpenDialog {
            get {
                return ((bool)(this["PauseRefreshWithOpenDialog"]));
            }
            set {
                this["PauseRefreshWithOpenDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HoldPrintLabel {
            get {
                return ((bool)(this["HoldPrintLabel"]));
            }
            set {
                this["HoldPrintLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedProcessPackage {
            get {
                return ((string)(this["LastSelectedProcessPackage"]));
            }
            set {
                this["LastSelectedProcessPackage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintPdfUsingReader {
            get {
                return ((bool)(this["PrintPdfUsingReader"]));
            }
        }
    }
}
