namespace DWOS.Dashboard
{
	partial class DailyRevenue
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if(disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
			Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
			Infragistics.UltraGauge.Resources.BoxAnnotation boxAnnotation1 = new Infragistics.UltraGauge.Resources.BoxAnnotation();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement1 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.BoxAnnotation boxAnnotation2 = new Infragistics.UltraGauge.Resources.BoxAnnotation();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement2 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGauge radialGauge1 = new Infragistics.UltraGauge.Resources.RadialGauge();
			Infragistics.UltraGauge.Resources.BrushElementGroup brushElementGroup1 = new Infragistics.UltraGauge.Resources.BrushElementGroup();
			Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement multiStopRadialGradientBrushElement1 = new Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DailyRevenue));
			Infragistics.UltraGauge.Resources.ColorStop colorStop1 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop2 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop3 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement3 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement multiStopRadialGradientBrushElement2 = new Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.ColorStop colorStop4 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop5 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop6 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop7 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop8 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop9 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement4 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGradientBrushElement radialGradientBrushElement1 = new Infragistics.UltraGauge.Resources.RadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeScale radialGaugeScale1 = new Infragistics.UltraGauge.Resources.RadialGaugeScale();
			Infragistics.UltraGauge.Resources.NumericAxis numericAxis1 = new Infragistics.UltraGauge.Resources.NumericAxis();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement5 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement6 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeNeedle radialGaugeNeedle1 = new Infragistics.UltraGauge.Resources.RadialGaugeNeedle();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement7 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement8 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement9 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement10 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement11 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeRange radialGaugeRange1 = new Infragistics.UltraGauge.Resources.RadialGaugeRange();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement12 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement13 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SegmentedDigitalGauge segmentedDigitalGauge1 = new Infragistics.UltraGauge.Resources.SegmentedDigitalGauge();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement14 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement15 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.BoxAnnotation boxAnnotation3 = new Infragistics.UltraGauge.Resources.BoxAnnotation();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement16 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.BoxAnnotation boxAnnotation4 = new Infragistics.UltraGauge.Resources.BoxAnnotation();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement17 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGauge radialGauge2 = new Infragistics.UltraGauge.Resources.RadialGauge();
			Infragistics.UltraGauge.Resources.BrushElementGroup brushElementGroup2 = new Infragistics.UltraGauge.Resources.BrushElementGroup();
			Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement multiStopRadialGradientBrushElement3 = new Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.ColorStop colorStop10 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop11 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop12 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement18 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement multiStopRadialGradientBrushElement4 = new Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.ColorStop colorStop13 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop14 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop15 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop16 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop17 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop18 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement19 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGradientBrushElement radialGradientBrushElement2 = new Infragistics.UltraGauge.Resources.RadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeScale radialGaugeScale2 = new Infragistics.UltraGauge.Resources.RadialGaugeScale();
			Infragistics.UltraGauge.Resources.NumericAxis numericAxis2 = new Infragistics.UltraGauge.Resources.NumericAxis();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement20 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement21 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeNeedle radialGaugeNeedle2 = new Infragistics.UltraGauge.Resources.RadialGaugeNeedle();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement22 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement23 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement24 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement25 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement26 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeRange radialGaugeRange2 = new Infragistics.UltraGauge.Resources.RadialGaugeRange();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement27 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement28 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SegmentedDigitalGauge segmentedDigitalGauge2 = new Infragistics.UltraGauge.Resources.SegmentedDigitalGauge();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement29 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement30 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.BoxAnnotation boxAnnotation5 = new Infragistics.UltraGauge.Resources.BoxAnnotation();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement31 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.BoxAnnotation boxAnnotation6 = new Infragistics.UltraGauge.Resources.BoxAnnotation();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement32 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGauge radialGauge3 = new Infragistics.UltraGauge.Resources.RadialGauge();
			Infragistics.UltraGauge.Resources.BrushElementGroup brushElementGroup3 = new Infragistics.UltraGauge.Resources.BrushElementGroup();
			Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement multiStopRadialGradientBrushElement5 = new Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.ColorStop colorStop19 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop20 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop21 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement33 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement multiStopRadialGradientBrushElement6 = new Infragistics.UltraGauge.Resources.MultiStopRadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.ColorStop colorStop22 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop23 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop24 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop25 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop26 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.ColorStop colorStop27 = new Infragistics.UltraGauge.Resources.ColorStop();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement34 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGradientBrushElement radialGradientBrushElement3 = new Infragistics.UltraGauge.Resources.RadialGradientBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeScale radialGaugeScale3 = new Infragistics.UltraGauge.Resources.RadialGaugeScale();
			Infragistics.UltraGauge.Resources.NumericAxis numericAxis3 = new Infragistics.UltraGauge.Resources.NumericAxis();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement35 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement36 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeNeedle radialGaugeNeedle3 = new Infragistics.UltraGauge.Resources.RadialGaugeNeedle();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement37 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement38 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement39 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement40 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement41 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.RadialGaugeRange radialGaugeRange3 = new Infragistics.UltraGauge.Resources.RadialGaugeRange();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement42 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement43 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SegmentedDigitalGauge segmentedDigitalGauge3 = new Infragistics.UltraGauge.Resources.SegmentedDigitalGauge();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement44 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraGauge.Resources.SolidFillBrushElement solidFillBrushElement45 = new Infragistics.UltraGauge.Resources.SolidFillBrushElement();
			Infragistics.UltraChart.Resources.Appearance.GradientEffect gradientEffect1 = new Infragistics.UltraChart.Resources.Appearance.GradientEffect();
			Infragistics.UltraChart.Resources.Appearance.PaintElement paintElement1 = new Infragistics.UltraChart.Resources.Appearance.PaintElement();
			Infragistics.UltraChart.Resources.Appearance.GradientEffect gradientEffect2 = new Infragistics.UltraChart.Resources.Appearance.GradientEffect();
			Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
			this.chkIncludeBoxed = new Infragistics.Win.UltraWinEditors.UltraCheckEditor();
			this.ultraLabel1 = new Infragistics.Win.Misc.UltraLabel();
			this.ultraLabel2 = new Infragistics.Win.Misc.UltraLabel();
			this.ultraLabel3 = new Infragistics.Win.Misc.UltraLabel();
			this.gaugeReceiving = new Infragistics.Win.UltraWinGauge.UltraGauge();
			this.ultraGauge1 = new Infragistics.Win.UltraWinGauge.UltraGauge();
			this.ultraGauge2 = new Infragistics.Win.UltraWinGauge.UltraGauge();
			this.ultraChart1 = new Infragistics.Win.UltraWinChart.UltraChart();
			this.ultraChart2 = new Infragistics.Win.UltraWinChart.UltraChart();
			this.ultraLabel4 = new Infragistics.Win.Misc.UltraLabel();
			((System.ComponentModel.ISupportInitialize)(this.chkIncludeBoxed)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.ultraChart1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.ultraChart2)).BeginInit();
			this.SuspendLayout();
			// 
			// chkIncludeBoxed
			// 
			this.chkIncludeBoxed.AutoSize = true;
			this.chkIncludeBoxed.Checked = true;
			this.chkIncludeBoxed.CheckState = System.Windows.Forms.CheckState.Checked;
			this.chkIncludeBoxed.Location = new System.Drawing.Point(3, 245);
			this.chkIncludeBoxed.Name = "chkIncludeBoxed";
			this.chkIncludeBoxed.Size = new System.Drawing.Size(62, 18);
			this.chkIncludeBoxed.TabIndex = 13;
			this.chkIncludeBoxed.Text = "Boxed";
			// 
			// ultraLabel1
			// 
			appearance1.FontData.BoldAsString = "True";
			appearance1.ForeColor = System.Drawing.Color.DarkRed;
			appearance1.TextHAlignAsString = "Center";
			this.ultraLabel1.Appearance = appearance1;
			this.ultraLabel1.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.ultraLabel1.Location = new System.Drawing.Point(28, 263);
			this.ultraLabel1.Name = "ultraLabel1";
			this.ultraLabel1.Size = new System.Drawing.Size(162, 20);
			this.ultraLabel1.TabIndex = 12;
			this.ultraLabel1.Text = "Current Day";
			// 
			// ultraLabel2
			// 
			appearance2.FontData.BoldAsString = "True";
			appearance2.ForeColor = System.Drawing.Color.DarkRed;
			appearance2.TextHAlignAsString = "Center";
			this.ultraLabel2.Appearance = appearance2;
			this.ultraLabel2.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.ultraLabel2.Location = new System.Drawing.Point(228, 263);
			this.ultraLabel2.Name = "ultraLabel2";
			this.ultraLabel2.Size = new System.Drawing.Size(162, 20);
			this.ultraLabel2.TabIndex = 17;
			this.ultraLabel2.Text = "Current Week";
			// 
			// ultraLabel3
			// 
			appearance3.FontData.BoldAsString = "True";
			appearance3.ForeColor = System.Drawing.Color.DarkRed;
			appearance3.TextHAlignAsString = "Center";
			this.ultraLabel3.Appearance = appearance3;
			this.ultraLabel3.Font = new System.Drawing.Font("Verdana", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.ultraLabel3.Location = new System.Drawing.Point(436, 266);
			this.ultraLabel3.Name = "ultraLabel3";
			this.ultraLabel3.Size = new System.Drawing.Size(162, 20);
			this.ultraLabel3.TabIndex = 18;
			this.ultraLabel3.Text = "Current Month";
			// 
			// gaugeReceiving
			// 
			boxAnnotation1.Bounds = new System.Drawing.Rectangle(134, 155, 0, 0);
			solidFillBrushElement1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(225)))), ((int)(((byte)(225)))));
			boxAnnotation1.Label.BrushElements.Add(solidFillBrushElement1);
			boxAnnotation1.Label.Font = new System.Drawing.Font("Arial", 7F, System.Drawing.FontStyle.Bold);
			boxAnnotation1.Label.FormatString = "K";
			boxAnnotation2.Bounds = new System.Drawing.Rectangle(65, 147, 0, 0);
			solidFillBrushElement2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(225)))), ((int)(((byte)(225)))));
			boxAnnotation2.Label.BrushElements.Add(solidFillBrushElement2);
			boxAnnotation2.Label.Font = new System.Drawing.Font("Arial", 11F);
			boxAnnotation2.Label.FormatString = "$";
			this.gaugeReceiving.Annotations.Add(boxAnnotation1);
			this.gaugeReceiving.Annotations.Add(boxAnnotation2);
			this.gaugeReceiving.BackColor = System.Drawing.Color.Transparent;
			this.gaugeReceiving.ForeColor = System.Drawing.SystemColors.ControlLightLight;
			multiStopRadialGradientBrushElement1.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement1.CenterPoint")));
			colorStop1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			colorStop2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(96)))), ((int)(((byte)(96)))));
			colorStop2.Stop = 0.4758621F;
			colorStop3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(89)))), ((int)(((byte)(89)))));
			colorStop3.Stop = 1F;
			multiStopRadialGradientBrushElement1.ColorStops.Add(colorStop1);
			multiStopRadialGradientBrushElement1.ColorStops.Add(colorStop2);
			multiStopRadialGradientBrushElement1.ColorStops.Add(colorStop3);
			multiStopRadialGradientBrushElement1.FocusScales = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement1.FocusScales")));
			solidFillBrushElement3.Color = System.Drawing.Color.Gray;
			solidFillBrushElement3.RelativeBounds = new System.Drawing.Rectangle(4, 4, 93, 93);
			solidFillBrushElement3.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			multiStopRadialGradientBrushElement2.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement2.CenterPoint")));
			colorStop4.Color = System.Drawing.Color.Transparent;
			colorStop5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
			colorStop5.Stop = 0.06206897F;
			colorStop6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(82)))), ((int)(((byte)(82)))));
			colorStop6.Stop = 0.07586207F;
			colorStop7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(45)))));
			colorStop7.Stop = 0.1448276F;
			colorStop8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
			colorStop8.Stop = 0.2448276F;
			colorStop9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
			colorStop9.Stop = 1F;
			multiStopRadialGradientBrushElement2.ColorStops.Add(colorStop4);
			multiStopRadialGradientBrushElement2.ColorStops.Add(colorStop5);
			multiStopRadialGradientBrushElement2.ColorStops.Add(colorStop6);
			multiStopRadialGradientBrushElement2.ColorStops.Add(colorStop7);
			multiStopRadialGradientBrushElement2.ColorStops.Add(colorStop8);
			multiStopRadialGradientBrushElement2.ColorStops.Add(colorStop9);
			multiStopRadialGradientBrushElement2.FocusScales = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement2.FocusScales")));
			multiStopRadialGradientBrushElement2.RelativeBounds = new System.Drawing.Rectangle(4, 4, 93, 93);
			multiStopRadialGradientBrushElement2.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			brushElementGroup1.BrushElements.Add(multiStopRadialGradientBrushElement1);
			brushElementGroup1.BrushElements.Add(solidFillBrushElement3);
			brushElementGroup1.BrushElements.Add(multiStopRadialGradientBrushElement2);
			radialGauge1.Dial.BrushElements.Add(brushElementGroup1);
			radialGauge1.Dial.Expansion = 0D;
			solidFillBrushElement4.Color = System.Drawing.Color.Silver;
			radialGauge1.Dial.StrokeElement.BrushElements.Add(solidFillBrushElement4);
			radialGradientBrushElement1.CenterColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			radialGradientBrushElement1.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("radialGradientBrushElement1.CenterPoint")));
			radialGradientBrushElement1.FocusScales = ((System.Drawing.PointF)(resources.GetObject("radialGradientBrushElement1.FocusScales")));
			radialGradientBrushElement1.RelativeBounds = new System.Drawing.Rectangle(16, 9, 70, 50);
			radialGradientBrushElement1.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGradientBrushElement1.SurroundColor = System.Drawing.Color.Transparent;
			radialGauge1.OverDial.BrushElements.Add(radialGradientBrushElement1);
			numericAxis1.EndValue = 100D;
			radialGaugeScale1.Axes.Add(numericAxis1);
			radialGaugeScale1.EndAngle = 405D;
			solidFillBrushElement5.Color = System.Drawing.Color.White;
			radialGaugeScale1.Labels.BrushElements.Add(solidFillBrushElement5);
			radialGaugeScale1.Labels.Extent = 73D;
			radialGaugeScale1.Labels.Font = new System.Drawing.Font("Arial", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
			radialGaugeScale1.Labels.FormatString = "<DATA_VALUE:0>K";
			radialGaugeScale1.Labels.Frequency = 20D;
			radialGaugeScale1.Labels.Orientation = Infragistics.UltraGauge.Resources.RadialLabelOrientation.Horizontal;
			radialGaugeScale1.Labels.SpanMaximum = 24D;
			solidFillBrushElement6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(189)))), ((int)(((byte)(189)))));
			radialGaugeScale1.MajorTickmarks.BrushElements.Add(solidFillBrushElement6);
			radialGaugeScale1.MajorTickmarks.EndExtent = 60D;
			radialGaugeScale1.MajorTickmarks.EndWidth = 3;
			radialGaugeScale1.MajorTickmarks.Frequency = 10D;
			radialGaugeScale1.MajorTickmarks.StartExtent = 50D;
			radialGaugeScale1.MajorTickmarks.StartWidth = 3;
			radialGaugeNeedle1.AllowDrag = true;
			solidFillBrushElement7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(90)))), ((int)(((byte)(57)))));
			radialGaugeNeedle1.Anchor.BrushElements.Add(solidFillBrushElement7);
			radialGaugeNeedle1.Anchor.Radius = 9D;
			radialGaugeNeedle1.Anchor.RadiusMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGaugeNeedle1.Anchor.StrokeElement.BrushElements.Add(solidFillBrushElement8);
			radialGaugeNeedle1.Anchor.StrokeElement.Thickness = 2D;
			solidFillBrushElement9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(90)))), ((int)(((byte)(57)))));
			radialGaugeNeedle1.BrushElements.Add(solidFillBrushElement9);
			radialGaugeNeedle1.EndExtent = 50D;
			radialGaugeNeedle1.MidExtent = 0D;
			radialGaugeNeedle1.MidWidth = 9D;
			radialGaugeNeedle1.Precision = 1D;
			radialGaugeNeedle1.StartWidth = 9D;
			radialGaugeNeedle1.StrokeElement.Thickness = 0D;
			radialGaugeNeedle1.Value = 68D;
			radialGaugeNeedle1.WidthMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGaugeScale1.Markers.Add(radialGaugeNeedle1);
			solidFillBrushElement10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			radialGaugeScale1.MinorTickmarks.BrushElements.Add(solidFillBrushElement10);
			radialGaugeScale1.MinorTickmarks.EndExtent = 52D;
			radialGaugeScale1.MinorTickmarks.EndWidth = 1;
			radialGaugeScale1.MinorTickmarks.Frequency = 5D;
			radialGaugeScale1.MinorTickmarks.StartExtent = 58D;
			solidFillBrushElement11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(135)))), ((int)(((byte)(135)))), ((int)(((byte)(135)))));
			radialGaugeScale1.MinorTickmarks.StrokeElement.BrushElements.Add(solidFillBrushElement11);
			solidFillBrushElement12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			radialGaugeRange1.BrushElements.Add(solidFillBrushElement12);
			radialGaugeRange1.EndValue = 100D;
			radialGaugeRange1.InnerExtentEnd = 50D;
			radialGaugeRange1.InnerExtentStart = 50D;
			radialGaugeRange1.OuterExtent = 60D;
			radialGaugeRange1.Shadow.BrushElements.Add(solidFillBrushElement13);
			radialGaugeRange1.StartValue = 0D;
			radialGaugeScale1.Ranges.Add(radialGaugeRange1);
			radialGaugeScale1.StartAngle = 135D;
			radialGauge1.Scales.Add(radialGaugeScale1);
			segmentedDigitalGauge1.Bounds = new System.Drawing.Rectangle(76, 146, 60, 22);
			solidFillBrushElement14.Color = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(195)))), ((int)(((byte)(195)))));
			segmentedDigitalGauge1.BrushElements.Add(solidFillBrushElement14);
			segmentedDigitalGauge1.Digits = 4;
			segmentedDigitalGauge1.DigitSpacing = 1D;
			solidFillBrushElement15.Color = System.Drawing.Color.DarkRed;
			segmentedDigitalGauge1.FontBrushElements.Add(solidFillBrushElement15);
			segmentedDigitalGauge1.Text = "0020";
			this.gaugeReceiving.Gauges.Add(radialGauge1);
			this.gaugeReceiving.Gauges.Add(segmentedDigitalGauge1);
			this.gaugeReceiving.Location = new System.Drawing.Point(7, 56);
			this.gaugeReceiving.Name = "gaugeReceiving";
			this.gaugeReceiving.Size = new System.Drawing.Size(199, 201);
			this.gaugeReceiving.TabIndex = 19;
			// 
			// ultraGauge1
			// 
			boxAnnotation3.Bounds = new System.Drawing.Rectangle(134, 155, 0, 0);
			solidFillBrushElement16.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(225)))), ((int)(((byte)(225)))));
			boxAnnotation3.Label.BrushElements.Add(solidFillBrushElement16);
			boxAnnotation3.Label.Font = new System.Drawing.Font("Arial", 7F, System.Drawing.FontStyle.Bold);
			boxAnnotation3.Label.FormatString = "K";
			boxAnnotation4.Bounds = new System.Drawing.Rectangle(65, 147, 0, 0);
			solidFillBrushElement17.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(225)))), ((int)(((byte)(225)))));
			boxAnnotation4.Label.BrushElements.Add(solidFillBrushElement17);
			boxAnnotation4.Label.Font = new System.Drawing.Font("Arial", 11F);
			boxAnnotation4.Label.FormatString = "$";
			this.ultraGauge1.Annotations.Add(boxAnnotation3);
			this.ultraGauge1.Annotations.Add(boxAnnotation4);
			this.ultraGauge1.BackColor = System.Drawing.Color.Transparent;
			this.ultraGauge1.ForeColor = System.Drawing.SystemColors.ControlLightLight;
			multiStopRadialGradientBrushElement3.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement3.CenterPoint")));
			colorStop10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			colorStop11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(96)))), ((int)(((byte)(96)))));
			colorStop11.Stop = 0.4758621F;
			colorStop12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(89)))), ((int)(((byte)(89)))));
			colorStop12.Stop = 1F;
			multiStopRadialGradientBrushElement3.ColorStops.Add(colorStop10);
			multiStopRadialGradientBrushElement3.ColorStops.Add(colorStop11);
			multiStopRadialGradientBrushElement3.ColorStops.Add(colorStop12);
			multiStopRadialGradientBrushElement3.FocusScales = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement3.FocusScales")));
			solidFillBrushElement18.Color = System.Drawing.Color.Gray;
			solidFillBrushElement18.RelativeBounds = new System.Drawing.Rectangle(4, 4, 93, 93);
			solidFillBrushElement18.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			multiStopRadialGradientBrushElement4.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement4.CenterPoint")));
			colorStop13.Color = System.Drawing.Color.Transparent;
			colorStop14.Color = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
			colorStop14.Stop = 0.06206897F;
			colorStop15.Color = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(82)))), ((int)(((byte)(82)))));
			colorStop15.Stop = 0.07586207F;
			colorStop16.Color = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(45)))));
			colorStop16.Stop = 0.1448276F;
			colorStop17.Color = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
			colorStop17.Stop = 0.2448276F;
			colorStop18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
			colorStop18.Stop = 1F;
			multiStopRadialGradientBrushElement4.ColorStops.Add(colorStop13);
			multiStopRadialGradientBrushElement4.ColorStops.Add(colorStop14);
			multiStopRadialGradientBrushElement4.ColorStops.Add(colorStop15);
			multiStopRadialGradientBrushElement4.ColorStops.Add(colorStop16);
			multiStopRadialGradientBrushElement4.ColorStops.Add(colorStop17);
			multiStopRadialGradientBrushElement4.ColorStops.Add(colorStop18);
			multiStopRadialGradientBrushElement4.FocusScales = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement4.FocusScales")));
			multiStopRadialGradientBrushElement4.RelativeBounds = new System.Drawing.Rectangle(4, 4, 93, 93);
			multiStopRadialGradientBrushElement4.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			brushElementGroup2.BrushElements.Add(multiStopRadialGradientBrushElement3);
			brushElementGroup2.BrushElements.Add(solidFillBrushElement18);
			brushElementGroup2.BrushElements.Add(multiStopRadialGradientBrushElement4);
			radialGauge2.Dial.BrushElements.Add(brushElementGroup2);
			radialGauge2.Dial.Expansion = 0D;
			solidFillBrushElement19.Color = System.Drawing.Color.Silver;
			radialGauge2.Dial.StrokeElement.BrushElements.Add(solidFillBrushElement19);
			radialGradientBrushElement2.CenterColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			radialGradientBrushElement2.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("radialGradientBrushElement2.CenterPoint")));
			radialGradientBrushElement2.FocusScales = ((System.Drawing.PointF)(resources.GetObject("radialGradientBrushElement2.FocusScales")));
			radialGradientBrushElement2.RelativeBounds = new System.Drawing.Rectangle(16, 9, 70, 50);
			radialGradientBrushElement2.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGradientBrushElement2.SurroundColor = System.Drawing.Color.Transparent;
			radialGauge2.OverDial.BrushElements.Add(radialGradientBrushElement2);
			numericAxis2.EndValue = 100D;
			radialGaugeScale2.Axes.Add(numericAxis2);
			radialGaugeScale2.EndAngle = 405D;
			solidFillBrushElement20.Color = System.Drawing.Color.White;
			radialGaugeScale2.Labels.BrushElements.Add(solidFillBrushElement20);
			radialGaugeScale2.Labels.Extent = 73D;
			radialGaugeScale2.Labels.Font = new System.Drawing.Font("Arial", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
			radialGaugeScale2.Labels.FormatString = "<DATA_VALUE:0>K";
			radialGaugeScale2.Labels.Frequency = 20D;
			radialGaugeScale2.Labels.Orientation = Infragistics.UltraGauge.Resources.RadialLabelOrientation.Horizontal;
			radialGaugeScale2.Labels.SpanMaximum = 24D;
			solidFillBrushElement21.Color = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(189)))), ((int)(((byte)(189)))));
			radialGaugeScale2.MajorTickmarks.BrushElements.Add(solidFillBrushElement21);
			radialGaugeScale2.MajorTickmarks.EndExtent = 60D;
			radialGaugeScale2.MajorTickmarks.EndWidth = 3;
			radialGaugeScale2.MajorTickmarks.Frequency = 10D;
			radialGaugeScale2.MajorTickmarks.StartExtent = 50D;
			radialGaugeScale2.MajorTickmarks.StartWidth = 3;
			radialGaugeNeedle2.AllowDrag = true;
			solidFillBrushElement22.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(90)))), ((int)(((byte)(57)))));
			radialGaugeNeedle2.Anchor.BrushElements.Add(solidFillBrushElement22);
			radialGaugeNeedle2.Anchor.Radius = 9D;
			radialGaugeNeedle2.Anchor.RadiusMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGaugeNeedle2.Anchor.StrokeElement.BrushElements.Add(solidFillBrushElement23);
			radialGaugeNeedle2.Anchor.StrokeElement.Thickness = 2D;
			solidFillBrushElement24.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(90)))), ((int)(((byte)(57)))));
			radialGaugeNeedle2.BrushElements.Add(solidFillBrushElement24);
			radialGaugeNeedle2.EndExtent = 50D;
			radialGaugeNeedle2.MidExtent = 0D;
			radialGaugeNeedle2.MidWidth = 9D;
			radialGaugeNeedle2.Precision = 1D;
			radialGaugeNeedle2.StartWidth = 9D;
			radialGaugeNeedle2.StrokeElement.Thickness = 0D;
			radialGaugeNeedle2.Value = 68D;
			radialGaugeNeedle2.WidthMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGaugeScale2.Markers.Add(radialGaugeNeedle2);
			solidFillBrushElement25.Color = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			radialGaugeScale2.MinorTickmarks.BrushElements.Add(solidFillBrushElement25);
			radialGaugeScale2.MinorTickmarks.EndExtent = 52D;
			radialGaugeScale2.MinorTickmarks.EndWidth = 1;
			radialGaugeScale2.MinorTickmarks.Frequency = 5D;
			radialGaugeScale2.MinorTickmarks.StartExtent = 58D;
			solidFillBrushElement26.Color = System.Drawing.Color.FromArgb(((int)(((byte)(135)))), ((int)(((byte)(135)))), ((int)(((byte)(135)))));
			radialGaugeScale2.MinorTickmarks.StrokeElement.BrushElements.Add(solidFillBrushElement26);
			solidFillBrushElement27.Color = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			radialGaugeRange2.BrushElements.Add(solidFillBrushElement27);
			radialGaugeRange2.EndValue = 100D;
			radialGaugeRange2.InnerExtentEnd = 50D;
			radialGaugeRange2.InnerExtentStart = 50D;
			radialGaugeRange2.OuterExtent = 60D;
			radialGaugeRange2.Shadow.BrushElements.Add(solidFillBrushElement28);
			radialGaugeRange2.StartValue = 0D;
			radialGaugeScale2.Ranges.Add(radialGaugeRange2);
			radialGaugeScale2.StartAngle = 135D;
			radialGauge2.Scales.Add(radialGaugeScale2);
			segmentedDigitalGauge2.Bounds = new System.Drawing.Rectangle(76, 146, 60, 22);
			solidFillBrushElement29.Color = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(195)))), ((int)(((byte)(195)))));
			segmentedDigitalGauge2.BrushElements.Add(solidFillBrushElement29);
			segmentedDigitalGauge2.Digits = 4;
			segmentedDigitalGauge2.DigitSpacing = 1D;
			solidFillBrushElement30.Color = System.Drawing.Color.DarkRed;
			segmentedDigitalGauge2.FontBrushElements.Add(solidFillBrushElement30);
			segmentedDigitalGauge2.Text = "0020";
			this.ultraGauge1.Gauges.Add(radialGauge2);
			this.ultraGauge1.Gauges.Add(segmentedDigitalGauge2);
			this.ultraGauge1.Location = new System.Drawing.Point(417, 56);
			this.ultraGauge1.Name = "ultraGauge1";
			this.ultraGauge1.Size = new System.Drawing.Size(199, 201);
			this.ultraGauge1.TabIndex = 20;
			// 
			// ultraGauge2
			// 
			boxAnnotation5.Bounds = new System.Drawing.Rectangle(134, 155, 0, 0);
			solidFillBrushElement31.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(225)))), ((int)(((byte)(225)))));
			boxAnnotation5.Label.BrushElements.Add(solidFillBrushElement31);
			boxAnnotation5.Label.Font = new System.Drawing.Font("Arial", 7F, System.Drawing.FontStyle.Bold);
			boxAnnotation5.Label.FormatString = "K";
			boxAnnotation6.Bounds = new System.Drawing.Rectangle(65, 147, 0, 0);
			solidFillBrushElement32.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(225)))), ((int)(((byte)(225)))));
			boxAnnotation6.Label.BrushElements.Add(solidFillBrushElement32);
			boxAnnotation6.Label.Font = new System.Drawing.Font("Arial", 11F);
			boxAnnotation6.Label.FormatString = "$";
			this.ultraGauge2.Annotations.Add(boxAnnotation5);
			this.ultraGauge2.Annotations.Add(boxAnnotation6);
			this.ultraGauge2.BackColor = System.Drawing.Color.Transparent;
			this.ultraGauge2.ForeColor = System.Drawing.SystemColors.ControlLightLight;
			multiStopRadialGradientBrushElement5.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement5.CenterPoint")));
			colorStop19.Color = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			colorStop20.Color = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(96)))), ((int)(((byte)(96)))));
			colorStop20.Stop = 0.4758621F;
			colorStop21.Color = System.Drawing.Color.FromArgb(((int)(((byte)(89)))), ((int)(((byte)(89)))), ((int)(((byte)(89)))));
			colorStop21.Stop = 1F;
			multiStopRadialGradientBrushElement5.ColorStops.Add(colorStop19);
			multiStopRadialGradientBrushElement5.ColorStops.Add(colorStop20);
			multiStopRadialGradientBrushElement5.ColorStops.Add(colorStop21);
			multiStopRadialGradientBrushElement5.FocusScales = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement5.FocusScales")));
			solidFillBrushElement33.Color = System.Drawing.Color.Gray;
			solidFillBrushElement33.RelativeBounds = new System.Drawing.Rectangle(4, 4, 93, 93);
			solidFillBrushElement33.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			multiStopRadialGradientBrushElement6.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement6.CenterPoint")));
			colorStop22.Color = System.Drawing.Color.Transparent;
			colorStop23.Color = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
			colorStop23.Stop = 0.06206897F;
			colorStop24.Color = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(82)))), ((int)(((byte)(82)))));
			colorStop24.Stop = 0.07586207F;
			colorStop25.Color = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(45)))));
			colorStop25.Stop = 0.1448276F;
			colorStop26.Color = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
			colorStop26.Stop = 0.2448276F;
			colorStop27.Color = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
			colorStop27.Stop = 1F;
			multiStopRadialGradientBrushElement6.ColorStops.Add(colorStop22);
			multiStopRadialGradientBrushElement6.ColorStops.Add(colorStop23);
			multiStopRadialGradientBrushElement6.ColorStops.Add(colorStop24);
			multiStopRadialGradientBrushElement6.ColorStops.Add(colorStop25);
			multiStopRadialGradientBrushElement6.ColorStops.Add(colorStop26);
			multiStopRadialGradientBrushElement6.ColorStops.Add(colorStop27);
			multiStopRadialGradientBrushElement6.FocusScales = ((System.Drawing.PointF)(resources.GetObject("multiStopRadialGradientBrushElement6.FocusScales")));
			multiStopRadialGradientBrushElement6.RelativeBounds = new System.Drawing.Rectangle(4, 4, 93, 93);
			multiStopRadialGradientBrushElement6.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			brushElementGroup3.BrushElements.Add(multiStopRadialGradientBrushElement5);
			brushElementGroup3.BrushElements.Add(solidFillBrushElement33);
			brushElementGroup3.BrushElements.Add(multiStopRadialGradientBrushElement6);
			radialGauge3.Dial.BrushElements.Add(brushElementGroup3);
			radialGauge3.Dial.Expansion = 0D;
			solidFillBrushElement34.Color = System.Drawing.Color.Silver;
			radialGauge3.Dial.StrokeElement.BrushElements.Add(solidFillBrushElement34);
			radialGradientBrushElement3.CenterColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			radialGradientBrushElement3.CenterPoint = ((System.Drawing.PointF)(resources.GetObject("radialGradientBrushElement3.CenterPoint")));
			radialGradientBrushElement3.FocusScales = ((System.Drawing.PointF)(resources.GetObject("radialGradientBrushElement3.FocusScales")));
			radialGradientBrushElement3.RelativeBounds = new System.Drawing.Rectangle(16, 9, 70, 50);
			radialGradientBrushElement3.RelativeBoundsMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGradientBrushElement3.SurroundColor = System.Drawing.Color.Transparent;
			radialGauge3.OverDial.BrushElements.Add(radialGradientBrushElement3);
			numericAxis3.EndValue = 100D;
			radialGaugeScale3.Axes.Add(numericAxis3);
			radialGaugeScale3.EndAngle = 405D;
			solidFillBrushElement35.Color = System.Drawing.Color.White;
			radialGaugeScale3.Labels.BrushElements.Add(solidFillBrushElement35);
			radialGaugeScale3.Labels.Extent = 73D;
			radialGaugeScale3.Labels.Font = new System.Drawing.Font("Arial", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
			radialGaugeScale3.Labels.FormatString = "<DATA_VALUE:0>K";
			radialGaugeScale3.Labels.Frequency = 20D;
			radialGaugeScale3.Labels.Orientation = Infragistics.UltraGauge.Resources.RadialLabelOrientation.Horizontal;
			radialGaugeScale3.Labels.SpanMaximum = 24D;
			solidFillBrushElement36.Color = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(189)))), ((int)(((byte)(189)))));
			radialGaugeScale3.MajorTickmarks.BrushElements.Add(solidFillBrushElement36);
			radialGaugeScale3.MajorTickmarks.EndExtent = 60D;
			radialGaugeScale3.MajorTickmarks.EndWidth = 3;
			radialGaugeScale3.MajorTickmarks.Frequency = 10D;
			radialGaugeScale3.MajorTickmarks.StartExtent = 50D;
			radialGaugeScale3.MajorTickmarks.StartWidth = 3;
			radialGaugeNeedle3.AllowDrag = true;
			solidFillBrushElement37.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(90)))), ((int)(((byte)(57)))));
			radialGaugeNeedle3.Anchor.BrushElements.Add(solidFillBrushElement37);
			radialGaugeNeedle3.Anchor.Radius = 9D;
			radialGaugeNeedle3.Anchor.RadiusMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGaugeNeedle3.Anchor.StrokeElement.BrushElements.Add(solidFillBrushElement38);
			radialGaugeNeedle3.Anchor.StrokeElement.Thickness = 2D;
			solidFillBrushElement39.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(90)))), ((int)(((byte)(57)))));
			radialGaugeNeedle3.BrushElements.Add(solidFillBrushElement39);
			radialGaugeNeedle3.EndExtent = 50D;
			radialGaugeNeedle3.MidExtent = 0D;
			radialGaugeNeedle3.MidWidth = 9D;
			radialGaugeNeedle3.Precision = 1D;
			radialGaugeNeedle3.StartWidth = 9D;
			radialGaugeNeedle3.StrokeElement.Thickness = 0D;
			radialGaugeNeedle3.Value = 68D;
			radialGaugeNeedle3.WidthMeasure = Infragistics.UltraGauge.Resources.Measure.Percent;
			radialGaugeScale3.Markers.Add(radialGaugeNeedle3);
			solidFillBrushElement40.Color = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			radialGaugeScale3.MinorTickmarks.BrushElements.Add(solidFillBrushElement40);
			radialGaugeScale3.MinorTickmarks.EndExtent = 52D;
			radialGaugeScale3.MinorTickmarks.EndWidth = 1;
			radialGaugeScale3.MinorTickmarks.Frequency = 5D;
			radialGaugeScale3.MinorTickmarks.StartExtent = 58D;
			solidFillBrushElement41.Color = System.Drawing.Color.FromArgb(((int)(((byte)(135)))), ((int)(((byte)(135)))), ((int)(((byte)(135)))));
			radialGaugeScale3.MinorTickmarks.StrokeElement.BrushElements.Add(solidFillBrushElement41);
			solidFillBrushElement42.Color = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			radialGaugeRange3.BrushElements.Add(solidFillBrushElement42);
			radialGaugeRange3.EndValue = 100D;
			radialGaugeRange3.InnerExtentEnd = 50D;
			radialGaugeRange3.InnerExtentStart = 50D;
			radialGaugeRange3.OuterExtent = 60D;
			radialGaugeRange3.Shadow.BrushElements.Add(solidFillBrushElement43);
			radialGaugeRange3.StartValue = 0D;
			radialGaugeScale3.Ranges.Add(radialGaugeRange3);
			radialGaugeScale3.StartAngle = 135D;
			radialGauge3.Scales.Add(radialGaugeScale3);
			segmentedDigitalGauge3.Bounds = new System.Drawing.Rectangle(76, 146, 60, 22);
			solidFillBrushElement44.Color = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(195)))), ((int)(((byte)(195)))));
			segmentedDigitalGauge3.BrushElements.Add(solidFillBrushElement44);
			segmentedDigitalGauge3.Digits = 4;
			segmentedDigitalGauge3.DigitSpacing = 1D;
			solidFillBrushElement45.Color = System.Drawing.Color.DarkRed;
			segmentedDigitalGauge3.FontBrushElements.Add(solidFillBrushElement45);
			segmentedDigitalGauge3.Text = "0020";
			this.ultraGauge2.Gauges.Add(radialGauge3);
			this.ultraGauge2.Gauges.Add(segmentedDigitalGauge3);
			this.ultraGauge2.Location = new System.Drawing.Point(212, 56);
			this.ultraGauge2.Name = "ultraGauge2";
			this.ultraGauge2.Size = new System.Drawing.Size(199, 201);
			this.ultraGauge2.TabIndex = 21;
			// 
//			'UltraChart' properties's serialization: Since 'ChartType' changes the way axes look,
//			'ChartType' must be persisted ahead of any Axes change made in design time.
//		
			this.ultraChart1.ChartType = Infragistics.UltraChart.Shared.Styles.ChartType.LineChart;
			// 
			// ultraChart1
			// 
			this.ultraChart1.Axis.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(220)))));
			this.ultraChart1.Axis.X.Extent = 37;
			this.ultraChart1.Axis.X.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.X.Labels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart1.Axis.X.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.X.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart1.Axis.X.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.X.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart1.Axis.X.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.X.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart1.Axis.X.Labels.SeriesLabels.FormatString = "";
			this.ultraChart1.Axis.X.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.X.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.X.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart1.Axis.X.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.X.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.X.LineThickness = 1;
			this.ultraChart1.Axis.X.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.X.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart1.Axis.X.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.X.MajorGridLines.Visible = true;
			this.ultraChart1.Axis.X.Margin.Far.Value = 1.1952191235059761D;
			this.ultraChart1.Axis.X.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.X.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart1.Axis.X.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.X.MinorGridLines.Visible = false;
			this.ultraChart1.Axis.X.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart1.Axis.X.Visible = true;
			this.ultraChart1.Axis.X2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.X2.Labels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart1.Axis.X2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart1.Axis.X2.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart1.Axis.X2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.X2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart1.Axis.X2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.X2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart1.Axis.X2.Labels.SeriesLabels.FormatString = "";
			this.ultraChart1.Axis.X2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart1.Axis.X2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.X2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart1.Axis.X2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.X2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.X2.Labels.Visible = false;
			this.ultraChart1.Axis.X2.LineThickness = 1;
			this.ultraChart1.Axis.X2.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.X2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart1.Axis.X2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.X2.MajorGridLines.Visible = true;
			this.ultraChart1.Axis.X2.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.X2.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart1.Axis.X2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.X2.MinorGridLines.Visible = false;
			this.ultraChart1.Axis.X2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart1.Axis.X2.Visible = false;
			this.ultraChart1.Axis.Y.Extent = 34;
			this.ultraChart1.Axis.Y.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Y.Labels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart1.Axis.Y.Labels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart1.Axis.Y.Labels.ItemFormatString = "<DATA_VALUE:00.##>K";
			this.ultraChart1.Axis.Y.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Y.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Y.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Y.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart1.Axis.Y.Labels.SeriesLabels.FormatString = "";
			this.ultraChart1.Axis.Y.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart1.Axis.Y.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Y.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Y.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Y.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Y.LineThickness = 1;
			this.ultraChart1.Axis.Y.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Y.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart1.Axis.Y.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Y.MajorGridLines.Visible = true;
			this.ultraChart1.Axis.Y.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Y.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart1.Axis.Y.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Y.MinorGridLines.Visible = false;
			this.ultraChart1.Axis.Y.TickmarkInterval = 50D;
			this.ultraChart1.Axis.Y.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart1.Axis.Y.Visible = true;
			this.ultraChart1.Axis.Y2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Y2.Labels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart1.Axis.Y2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.Y2.Labels.ItemFormatString = "<DATA_VALUE:00.##>";
			this.ultraChart1.Axis.Y2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Y2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Y2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Y2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart1.Axis.Y2.Labels.SeriesLabels.FormatString = "";
			this.ultraChart1.Axis.Y2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.Y2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Y2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Y2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Y2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Y2.Labels.Visible = false;
			this.ultraChart1.Axis.Y2.LineThickness = 1;
			this.ultraChart1.Axis.Y2.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Y2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart1.Axis.Y2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Y2.MajorGridLines.Visible = true;
			this.ultraChart1.Axis.Y2.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Y2.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart1.Axis.Y2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Y2.MinorGridLines.Visible = false;
			this.ultraChart1.Axis.Y2.TickmarkInterval = 50D;
			this.ultraChart1.Axis.Y2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart1.Axis.Y2.Visible = false;
			this.ultraChart1.Axis.Z.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Z.Labels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart1.Axis.Z.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.Z.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart1.Axis.Z.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Z.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Z.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Z.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart1.Axis.Z.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.Z.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Z.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Z.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Z.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Z.Labels.Visible = false;
			this.ultraChart1.Axis.Z.LineThickness = 1;
			this.ultraChart1.Axis.Z.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Z.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart1.Axis.Z.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Z.MajorGridLines.Visible = true;
			this.ultraChart1.Axis.Z.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Z.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart1.Axis.Z.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Z.MinorGridLines.Visible = false;
			this.ultraChart1.Axis.Z.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart1.Axis.Z.Visible = false;
			this.ultraChart1.Axis.Z2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Z2.Labels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart1.Axis.Z2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.Z2.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart1.Axis.Z2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Z2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Z2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart1.Axis.Z2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart1.Axis.Z2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart1.Axis.Z2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart1.Axis.Z2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart1.Axis.Z2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Z2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart1.Axis.Z2.Labels.Visible = false;
			this.ultraChart1.Axis.Z2.LineThickness = 1;
			this.ultraChart1.Axis.Z2.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Z2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart1.Axis.Z2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Z2.MajorGridLines.Visible = true;
			this.ultraChart1.Axis.Z2.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart1.Axis.Z2.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart1.Axis.Z2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart1.Axis.Z2.MinorGridLines.Visible = false;
			this.ultraChart1.Axis.Z2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart1.Axis.Z2.Visible = false;
			this.ultraChart1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
			this.ultraChart1.ColorModel.AlphaLevel = ((byte)(150));
			this.ultraChart1.ColorModel.ColorBegin = System.Drawing.Color.Pink;
			this.ultraChart1.ColorModel.ColorEnd = System.Drawing.Color.DarkRed;
			this.ultraChart1.ColorModel.ModelStyle = Infragistics.UltraChart.Shared.Styles.ColorModels.CustomLinear;
			this.ultraChart1.Effects.Effects.Add(gradientEffect1);
			this.ultraChart1.Location = new System.Drawing.Point(7, 303);
			this.ultraChart1.Name = "ultraChart1";
			this.ultraChart1.Size = new System.Drawing.Size(605, 162);
			this.ultraChart1.TabIndex = 22;
			this.ultraChart1.Tooltips.HighlightFillColor = System.Drawing.Color.DimGray;
			this.ultraChart1.Tooltips.HighlightOutlineColor = System.Drawing.Color.DarkGray;
			this.ultraChart1.Tooltips.TooltipControl = null;
			// 
//			'UltraChart' properties's serialization: Since 'ChartType' changes the way axes look,
//			'ChartType' must be persisted ahead of any Axes change made in design time.
//		
			this.ultraChart2.ChartType = Infragistics.UltraChart.Shared.Styles.ChartType.LineChart;
			// 
			// ultraChart2
			// 
			this.ultraChart2.Axis.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(220)))));
			paintElement1.ElementType = Infragistics.UltraChart.Shared.Styles.PaintElementType.None;
			paintElement1.Fill = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(220)))));
			this.ultraChart2.Axis.PE = paintElement1;
			this.ultraChart2.Axis.X.Extent = 37;
			this.ultraChart2.Axis.X.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.X.Labels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart2.Axis.X.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.X.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart2.Axis.X.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.X.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart2.Axis.X.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.X.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart2.Axis.X.Labels.SeriesLabels.FormatString = "";
			this.ultraChart2.Axis.X.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.X.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.X.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart2.Axis.X.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.X.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.X.LineThickness = 1;
			this.ultraChart2.Axis.X.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.X.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart2.Axis.X.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.X.MajorGridLines.Visible = true;
			this.ultraChart2.Axis.X.Margin.Far.Value = 1.1952191235059761D;
			this.ultraChart2.Axis.X.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.X.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart2.Axis.X.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.X.MinorGridLines.Visible = false;
			this.ultraChart2.Axis.X.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart2.Axis.X.Visible = true;
			this.ultraChart2.Axis.X2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.X2.Labels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart2.Axis.X2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart2.Axis.X2.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart2.Axis.X2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.X2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart2.Axis.X2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.X2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart2.Axis.X2.Labels.SeriesLabels.FormatString = "";
			this.ultraChart2.Axis.X2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart2.Axis.X2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.X2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
			this.ultraChart2.Axis.X2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.X2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.X2.Labels.Visible = false;
			this.ultraChart2.Axis.X2.LineThickness = 1;
			this.ultraChart2.Axis.X2.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.X2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart2.Axis.X2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.X2.MajorGridLines.Visible = true;
			this.ultraChart2.Axis.X2.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.X2.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart2.Axis.X2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.X2.MinorGridLines.Visible = false;
			this.ultraChart2.Axis.X2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart2.Axis.X2.Visible = false;
			this.ultraChart2.Axis.Y.Extent = 34;
			this.ultraChart2.Axis.Y.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Y.Labels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart2.Axis.Y.Labels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart2.Axis.Y.Labels.ItemFormatString = "<DATA_VALUE:00.##>K";
			this.ultraChart2.Axis.Y.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Y.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Y.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Y.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart2.Axis.Y.Labels.SeriesLabels.FormatString = "";
			this.ultraChart2.Axis.Y.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Far;
			this.ultraChart2.Axis.Y.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Y.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Y.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Y.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Y.LineThickness = 1;
			this.ultraChart2.Axis.Y.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Y.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart2.Axis.Y.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Y.MajorGridLines.Visible = true;
			this.ultraChart2.Axis.Y.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Y.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart2.Axis.Y.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Y.MinorGridLines.Visible = false;
			this.ultraChart2.Axis.Y.TickmarkInterval = 100D;
			this.ultraChart2.Axis.Y.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart2.Axis.Y.Visible = true;
			this.ultraChart2.Axis.Y2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Y2.Labels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart2.Axis.Y2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.Y2.Labels.ItemFormatString = "<DATA_VALUE:00.##>";
			this.ultraChart2.Axis.Y2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Y2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Y2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Y2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart2.Axis.Y2.Labels.SeriesLabels.FormatString = "";
			this.ultraChart2.Axis.Y2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.Y2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Y2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Y2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Y2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Y2.Labels.Visible = false;
			this.ultraChart2.Axis.Y2.LineThickness = 1;
			this.ultraChart2.Axis.Y2.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Y2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart2.Axis.Y2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Y2.MajorGridLines.Visible = true;
			this.ultraChart2.Axis.Y2.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Y2.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart2.Axis.Y2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Y2.MinorGridLines.Visible = false;
			this.ultraChart2.Axis.Y2.TickmarkInterval = 100D;
			this.ultraChart2.Axis.Y2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart2.Axis.Y2.Visible = false;
			this.ultraChart2.Axis.Z.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Z.Labels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart2.Axis.Z.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.Z.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart2.Axis.Z.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Z.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Z.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Z.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
			this.ultraChart2.Axis.Z.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.Z.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Z.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Z.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Z.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Z.Labels.Visible = false;
			this.ultraChart2.Axis.Z.LineThickness = 1;
			this.ultraChart2.Axis.Z.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Z.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart2.Axis.Z.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Z.MajorGridLines.Visible = true;
			this.ultraChart2.Axis.Z.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Z.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart2.Axis.Z.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Z.MinorGridLines.Visible = false;
			this.ultraChart2.Axis.Z.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart2.Axis.Z.Visible = false;
			this.ultraChart2.Axis.Z2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Z2.Labels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart2.Axis.Z2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.Z2.Labels.ItemFormatString = "<ITEM_LABEL>";
			this.ultraChart2.Axis.Z2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Z2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Z2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
			this.ultraChart2.Axis.Z2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
			this.ultraChart2.Axis.Z2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
			this.ultraChart2.Axis.Z2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
			this.ultraChart2.Axis.Z2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
			this.ultraChart2.Axis.Z2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Z2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
			this.ultraChart2.Axis.Z2.Labels.Visible = false;
			this.ultraChart2.Axis.Z2.LineThickness = 1;
			this.ultraChart2.Axis.Z2.MajorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Z2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
			this.ultraChart2.Axis.Z2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Z2.MajorGridLines.Visible = true;
			this.ultraChart2.Axis.Z2.MinorGridLines.AlphaLevel = ((byte)(255));
			this.ultraChart2.Axis.Z2.MinorGridLines.Color = System.Drawing.Color.LightGray;
			this.ultraChart2.Axis.Z2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
			this.ultraChart2.Axis.Z2.MinorGridLines.Visible = false;
			this.ultraChart2.Axis.Z2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
			this.ultraChart2.Axis.Z2.Visible = false;
			this.ultraChart2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
			this.ultraChart2.ColorModel.AlphaLevel = ((byte)(150));
			this.ultraChart2.ColorModel.ColorBegin = System.Drawing.Color.Pink;
			this.ultraChart2.ColorModel.ColorEnd = System.Drawing.Color.DarkRed;
			this.ultraChart2.ColorModel.ModelStyle = Infragistics.UltraChart.Shared.Styles.ColorModels.CustomLinear;
			this.ultraChart2.Effects.Effects.Add(gradientEffect2);
			this.ultraChart2.Location = new System.Drawing.Point(7, 471);
			this.ultraChart2.Name = "ultraChart2";
			this.ultraChart2.Size = new System.Drawing.Size(605, 147);
			this.ultraChart2.TabIndex = 23;
			this.ultraChart2.Tooltips.HighlightFillColor = System.Drawing.Color.DimGray;
			this.ultraChart2.Tooltips.HighlightOutlineColor = System.Drawing.Color.DarkGray;
			// 
			// ultraLabel4
			// 
			appearance4.BackColor = System.Drawing.Color.Firebrick;
			appearance4.ForeColor = System.Drawing.Color.WhiteSmoke;
			appearance4.TextHAlignAsString = "Center";
			appearance4.TextVAlignAsString = "Top";
			this.ultraLabel4.Appearance = appearance4;
			this.ultraLabel4.Dock = System.Windows.Forms.DockStyle.Top;
			this.ultraLabel4.Font = new System.Drawing.Font("Verdana", 27.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.ultraLabel4.Location = new System.Drawing.Point(0, 0);
			this.ultraLabel4.Name = "ultraLabel4";
			this.ultraLabel4.Size = new System.Drawing.Size(628, 50);
			this.ultraLabel4.TabIndex = 24;
			this.ultraLabel4.Text = "Revenue";
			this.ultraLabel4.UseAppStyling = false;
			// 
			// DailyRevenue
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = System.Drawing.SystemColors.ControlDark;
			this.Controls.Add(this.ultraLabel4);
			this.Controls.Add(this.ultraChart2);
			this.Controls.Add(this.ultraChart1);
			this.Controls.Add(this.ultraGauge2);
			this.Controls.Add(this.ultraGauge1);
			this.Controls.Add(this.ultraLabel3);
			this.Controls.Add(this.ultraLabel2);
			this.Controls.Add(this.chkIncludeBoxed);
			this.Controls.Add(this.ultraLabel1);
			this.Controls.Add(this.gaugeReceiving);
			this.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Name = "DailyRevenue";
			this.Size = new System.Drawing.Size(628, 638);
			((System.ComponentModel.ISupportInitialize)(this.chkIncludeBoxed)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.ultraChart1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.ultraChart2)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private Infragistics.Win.UltraWinEditors.UltraCheckEditor chkIncludeBoxed;
		private Infragistics.Win.Misc.UltraLabel ultraLabel1;
		private Infragistics.Win.Misc.UltraLabel ultraLabel2;
		private Infragistics.Win.Misc.UltraLabel ultraLabel3;
		private Infragistics.Win.UltraWinGauge.UltraGauge gaugeReceiving;
		private Infragistics.Win.UltraWinGauge.UltraGauge ultraGauge1;
		private Infragistics.Win.UltraWinGauge.UltraGauge ultraGauge2;
		private Infragistics.Win.UltraWinChart.UltraChart ultraChart1;
		private Infragistics.Win.UltraWinChart.UltraChart ultraChart2;
		private Infragistics.Win.Misc.UltraLabel ultraLabel4;
	}
}
